name: su
version: "${version}"
main: com.spectrasonic.su.Main
api-version: "1.21"
authors: [Spectrasonic]
commands:
    su:
        permission: su.command
permissions:
    su.command:
        default: true
